### ISSUE TITLE
[Google] s_byte with full_range="True" does not include 255 (0xff)	

### ISSUE THREAD

**Issue by Fitblip** [OpenRCE/sulley#21]
**What steps will reproduce the problem?**
1. create a block with an s_byte("\x00", full_range="True") in it
2. I use the session_file() class to output to a file

**What is the expected output? What do you see instead?**
I expected 256 packets to be created (0-255).  I got 0-254.

**What version of the product are you using? On what operating system?**
Latest, I think.  Windows.

**Please provide any additional information below.**
I think the xrange(start, stop) used in primitives.py is the problem.  It
does not include the stop value.

**Comment by SteveJM** [comment]
This is because xrange goes from start to end-1 and end is set to "max_num", which is set to the decimal value of "1" * width.  i.e. for a byte it will be set to "11111111" = 255. Either "max_num" nees to be set to 2^width (i.e. 256) - this will require one other fix in "add_integer_boundaries" that (falsely ?) accounts for needing to include the max value. Or, when building the range, "xrange" needs to be given arguments of "0, self.max_num+1".  I would favour the former.

**Comment by SteveJM** [comment]
A pull request has been submitted that resolves this.

**Comment by SteveJM** [comment]
This can now be closed.

**Comment by Fitblip** [comment]
Ah, good catch @SteveJM. Thanks again for the PR! :)
